ContosoUniversity/Models/Enrollment.cs
namespace ContosoUniversity.Models
{
    public enum Grade
    {
        A, B, C, D, F
    }

    public class Enrollment
    {
        public int EnrollmentID { get; set; }
        public int CourseID { get; set; }
        public int StudentID { get; set; }
        public Grade? Grade { get; set; }

        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}

ContosoUniversity/Controllers/EnrollmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using PagedList;
using System.Web.Mvc;
using ContosoUniversity.DAL;
using ContosoUniversity.Models;
using System.Data.Entity.Infrastructure;

namespace ContosoUniversity.Controllers
{
    public class EnrollmentController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: Student
        public ViewResult Index(string sortOrder, string currentFilter, string searchString)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.TitleSortParm = sortOrder == "Title" ? "title_desc" : "Title";
            ViewBag.GradeSortParm = sortOrder == "Grade" ? "grade_desc" : "Grade";
            ViewBag.CurrentFilter = searchString;
            var enroll = from s in db.Enrollments
                         select s;
            if (!String.IsNullOrEmpty(searchString))
            {

               enroll = enroll.Where(s => s.Student.LastName.Contains(searchString)
                                       || s.Course.Title.Contains(searchString));  
            }
            switch (sortOrder)
            {
                case "name_desc":
                    enroll = enroll.OrderByDescending(s => s.Student.LastName);
                    break;
                case "title_desc":
                    enroll = enroll.OrderByDescending(s => s.Course.Title);
                    break;
                case "Title":
                    enroll = enroll.OrderBy(s => s.Course.Title);
                    break;
                case "Grade":
                    enroll = enroll.OrderBy(s => s.Grade);
                    break;
                case "grade_desc":
                    enroll = enroll.OrderByDescending(s => s.Grade);
                    break;
                default:
                    enroll = enroll.OrderBy(s => s.Student.LastName);
                    break;
            }

            var enrollments = db.Enrollments.Include(s => s.Course).Include(s => s.Student);
            return View(enroll.ToList());
        }

        private DateTime? tokenize_and_extract_date_end(string searchString)
        {
            throw new NotImplementedException();
        }

        // GET: Student/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enroll = db.Enrollments.Find(id);
            if (enroll == null)
            {
                return HttpNotFound();
            }
            return View(enroll);
        }

        // GET: Student/Create
        public ActionResult Create()
        {
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Title");
            ViewBag.StudentID = new SelectList(db.Students, "ID", "LastName");
            return View();
        }

        // POST: Student/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EnrollmentID,CourseID,StudentID,Grade")] Enrollment enroll)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Enrollments.Add(enroll);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (RetryLimitExceededException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Title", enroll.CourseID);
            ViewBag.StudentID = new SelectList(db.Students, "ID", "LastName", enroll.StudentID);
            return View(enroll);
        }

        // GET: Student/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enroll = db.Enrollments.Find(id);
            if (enroll == null)
            {
                return HttpNotFound();
            }

            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Title", enroll.CourseID);
            ViewBag.StudentID = new SelectList(db.Students, "ID", "LastName", enroll.StudentID);
            return View(enroll);
        }

        // POST: Student/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var enrollToUpdate = db.Enrollments.Find(id);
            if (TryUpdateModel(enrollToUpdate, "",
               new string[] { "EnrollmentID", "CourseID", "StudentID", "Grade" }))
            {
                try
                {
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (DataException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Title", enrollToUpdate.CourseID);
            ViewBag.StudentID = new SelectList(db.Students, "ID", "LastName", enrollToUpdate.StudentID);
            return View(enrollToUpdate);
        }

        // GET: Student/Delete/5
        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persists see your system administrator.";
            }
            Enrollment enroll = db.Enrollments.Find(id);
            if (enroll == null)
            {
                return HttpNotFound();
            }
            return View(enroll);
        }

        // POST: Student/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                Enrollment enroll = db.Enrollments.Find(id);
                db.Enrollments.Remove(enroll);
                db.SaveChanges();
            }
            catch (DataException/* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ContosoUniversity/Views/Enrollment/Create.cshtml
@model ContosoUniversity.Models.Enrollment

@{
    ViewBag.Title = "Create";
}

<div class="page-header">
    <h2>Create <small>Enrollment</small></h2>
</div>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CourseID, "CourseID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentID, "StudentID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Grade, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ContosoUniversity/Views/Enrollment/Delete.cshtml
@model ContosoUniversity.Models.Enrollment

@{
    ViewBag.Title = "Delete";
}

<div class="page-header">
    <h2>Delete <small>Enrollment</small></h2>
    <h5 class="text-danger text-muted">Are you sure you want to delete this?</h5>
</div>

<h3>Are you sure you want to delete this?</h3>
<div>
    <dl class="dl-horizontal">
        <dt style="margin-bottom: 5px;">
            @Html.DisplayNameFor(model => model.Course.Title):
        </dt>

        <dd style="margin-bottom: 5px;">
            @Html.DisplayFor(model => model.Course.Title)
        </dd>

        <dt style="margin-bottom: 5px;">
            @Html.DisplayNameFor(model => model.Student.LastName):
        </dt>

        <dd style="margin-bottom: 5px;">
            @Html.DisplayFor(model => model.Student.LastName)
        </dd>

        <dt style="margin-bottom: 5px;">
            @Html.DisplayNameFor(model => model.Grade):
        </dt>

        <dd style="margin-bottom: 5px;">
            @Html.DisplayFor(model => model.Grade)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ContosoUniversity/Views/Enrollment/Details.cshtml
@model ContosoUniversity.Models.Enrollment

@{
    ViewBag.Title = "Details";
}

<div class="page-header">
    <h2>Details <small>Enrollment</small></h2>
</div>

<div>
    <dl class="dl-horizontal">
        <dt style="margin-bottom: 5px;">
            @Html.DisplayNameFor(model => model.Course.Title):
        </dt>

        <dd style="margin-bottom: 5px;">
            @Html.DisplayFor(model => model.Course.Title)
        </dd>

        <dt style="margin-bottom: 5px;">
            @Html.DisplayNameFor(model => model.Student.LastName):
        </dt>

        <dd style="margin-bottom: 5px;">
            @Html.DisplayFor(model => model.Student.LastName)
        </dd>

        <dt style="margin-bottom: 5px;">
            @Html.DisplayNameFor(model => model.Grade):
        </dt>

        <dd style="margin-bottom: 5px;">
            @Html.DisplayFor(model => model.Grade)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EnrollmentID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ContosoUniversity/Views/Enrollment/Edit.cshtml
@model ContosoUniversity.Models.Enrollment

@{
    ViewBag.Title = "Edit";
}

<div class="page-header">
    <h2>Edit <small>Enrollment</small></h2>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EnrollmentID)

        <div class="form-group">
            @Html.LabelFor(model => model.CourseID, "CourseID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentID, "StudentID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Grade, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ContosoUniversity/Views/Enrollment/Index.cshtml
@model IEnumerable<ContosoUniversity.Models.Enrollment>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}

<div class="page-header">
    <h2>Enrollment <small>Data Enrollment</small></h2>
</div>


@using (Html.BeginForm("Index", "Enrollment", FormMethod.Get))
{
    <p>
        <small>Find by Title or Lastname:</small> @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input class="btn btn-info btn-sm" type="submit" value="Search"/> |
        <a>@Html.ActionLink("Back to Full List", "Index", "Enrollment")</a>
    </p>
}
<h4>
    <span class="label label-info">@Html.ActionLink("Create New", "Create")</span>
</h4>
<div class="table-responsive">
    <table class="table table-bordered table-hover">
        <tr class="info">
            <th>
                @Html.ActionLink("Title", "Index", new { sortOrder = ViewBag.TitleSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Lastname", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Grade", "Index", new { sortOrder = ViewBag.GradeSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th class="text-center">
                Action
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Course.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Student.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Grade)
                </td>
                <td class="text-center">
                    @Html.ActionLink("Edit", "Edit", new { id = item.EnrollmentID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.EnrollmentID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.EnrollmentID })
                </td>
            </tr>
        }

    </table>
</div>